#
# Makefile for simple example in which bodies take their colour
# value from which voronoi grid region they belong to
#

CC=g++
CFLAGS=
LFLAGS=-lglut

all:
	$(CC) $(CFLAGS) simpleGL.cpp -o simpleGL $(LFLAGS)

clean:
	rm -rf *o *png simpleGL
